version: '3'
services:
  influxdb:
    image: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    volumes:
      - "./influxdb:/var/lib/influxdb"
      - "./influxdb.conf:/etc/influxdb/influxdb.conf"
  telegraf:
    image: telegraf
    container_name: sysmon_telegraf
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
  grafana:
    image: grafana/grafana
    ports:
      - "3030:3000"
    volumes:
      - "./grafana:/var/lib/grafana"
    user: "472"
